set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/vim-tmux-navigator'
set -g @plugin 'arcticicestudio/nord-tmux'


bind r
bind r source-file ~/.tmux.conf

set -g prefix M-s

set-option -sa terminal-overrides ",xterm*Tc"

run '~/.tmux/plugins/tpm/tpm'
